# Logging for Staging
logging.level.root=INFO
logging.level.com.bridgelabz.EmployeePayRollapp=INFO
logging.file.name=logs/staging.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [%level] - %msg%n
