# Logging for Production
logging.level.root=WARN
logging.level.com.bridgelabz.EmployeePayRollapp=ERROR
logging.file.name=logs/production.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
